---
- name: Install PostgreSQL 15 and create database/user on Amazon Linux
  hosts: db_server
  become: yes
  tasks:
    - name: Install PostgreSQL 15
      dnf:
        name: postgresql15-server
        state: present

    - name: Remove any existing PostgreSQL data directory
      file:
        path: /var/lib/pgsql/data
        state: absent
      ignore_errors: yes

    - name: Create PostgreSQL data directory
      file:
        path: /var/lib/pgsql/data
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    - name: Initialize PostgreSQL database
      command: /usr/bin/postgresql-setup initdb
      become: yes

    - name: Ensure PostgreSQL is running and enabled on boot
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Create a PostgreSQL database
      postgresql_db:
        name: mydatabase
        state: present
      become_user: postgres

    - name: Create a PostgreSQL superuser named OSCAR
      postgresql_user:
        name: OSCAR
        password: oscar_password
        state: present
        role_attr_flags: SUPERUSER
      become_user: postgres

